# This file was generated by GoReleaser. DO NOT EDIT.
cask "readback" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "9db580294e3a8e523be5769dad70da0ad4cfdb21aaed72edde2dd9e7d153531e"
      url "https://github.com/joshduffy/readback/releases/download/v#{version}/readback_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6eb4300de96d6c224a2e9112ef7fbcf552dd24c564c6c6479e01021eee7f8c7d"
      url "https://github.com/joshduffy/readback/releases/download/v#{version}/readback_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "adef60aeea8b6fc9c899816eb06871fa116dd47146fcc1da62c50803c8cc917f"
      url "https://github.com/joshduffy/readback/releases/download/v#{version}/readback_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ad10599ee2cfc4799c37dbd2953cefa067a08b60949a0560c14bd12dcdd273e"
      url "https://github.com/joshduffy/readback/releases/download/v#{version}/readback_#{version}_linux_amd64.tar.gz"
    end
  end

  name "readback"
  desc "Check coding agent claims against files, GitHub, and web responses"
  homepage "https://readbackcli.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "readback"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/readback"]
    end
  end

  # No zap stanza required
end
