# This file was generated by GoReleaser. DO NOT EDIT.
cask "readback" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "f3fc3ae50e07cbc6fce1c5ab217f8067cea3059d4dde2a01f396469a5fa2cbcd"
      url "https://github.com/joshduffy/readback/releases/download/v#{version}/readback_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "519f8b6134a72662b651d21c5c1e070a41b40267ce8840233525996031e1c0b3"
      url "https://github.com/joshduffy/readback/releases/download/v#{version}/readback_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ace6c84a7fb391ea88ec4f092894adb714a46c46d09f3728ec50702ce8a85a9b"
      url "https://github.com/joshduffy/readback/releases/download/v#{version}/readback_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d3a548599d3a2f6c6d7c6847dd17d9e825d4c22c757e4853a84d50ce9d97cf8f"
      url "https://github.com/joshduffy/readback/releases/download/v#{version}/readback_#{version}_linux_amd64.tar.gz"
    end
  end

  name "readback"
  desc "Agent ops for your own machine. Agents claim; readback verifies."
  homepage "https://github.com/joshduffy/readback"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "readback"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/readback"]
    end
  end

  # No zap stanza required
end
