# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Readback < Formula
  desc "Agent ops for your own machine. Agents claim; readback verifies."
  homepage "https://github.com/joshduffy/readback"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joshduffy/readback/releases/download/v0.1.3/readback_0.1.3_darwin_amd64.tar.gz"
      sha256 "373700d47d8a3da9eaaca52f3c3672f58185294c4bf9ab4f93ff15812f0fd595"

      define_method(:install) do
        bin.install "readback"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joshduffy/readback/releases/download/v0.1.3/readback_0.1.3_darwin_arm64.tar.gz"
      sha256 "643d4edccd5f4b4ca3b81b6bb68ecb90d85c9f6a1cb58059e2847ccbe886639d"

      define_method(:install) do
        bin.install "readback"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshduffy/readback/releases/download/v0.1.3/readback_0.1.3_linux_amd64.tar.gz"
      sha256 "6de1ade424f2ad6ff027f3dd2727258e587571c2ce1cfe063e6f004a03edf9ce"
      define_method(:install) do
        bin.install "readback"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshduffy/readback/releases/download/v0.1.3/readback_0.1.3_linux_arm64.tar.gz"
      sha256 "25c37bb74be018f6e863d4a3dabf356d038e2be4038f1c86245b2890d0a73b78"
      define_method(:install) do
        bin.install "readback"
      end
    end
  end

  test do
    system "#{bin}/readback", "capabilities", "--json"
  end
end
